version: '3'

services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d

  tomcat:
    build: .
    container_name: tomcat
    restart: always
    ports:
      - "8080:8080"
